version: "3.7"

services:
  db_rentalx:
    image: postgres
    container_name: db_rentalx
    restart: always
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=rentalx
      - POSTGRES_PASSWORD=rentalx
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local